### ISSUE TITLE
messenger.com and facebook.com should be equivalent domains

### ISSUE THREAD

**Issue by forabi** [bitwarden/core#34] opened 2017-02-23 22:48 UTC
https://www.messenger.com is the official Facebook messenger web app and can be logged in using Facebook credentials.

**Comment by sreich** [comment] 2017-02-23 22:50
Duplicate of #19

**Comment by kspearrin** [comment] 2017-02-24 00:34
This has been resolved with the introduction of equivalent domains. It has been rolled out on the web vault and Android at this time and will eventually make its way to browsers with v1.9.x

**Closed by kspearrin** 2017-02-24 00:34 UTC

**Comment by kruge002** [comment] 2018-07-10 07:56
I found it under settings - Domain Rules in the web vault.

Please add an article about equivalent domains to the Bitwarden Help pages at [help.bitwarden.com](https://help.bitwarden.com/)
