### ISSUE TITLE
Support certificate pinning

### ISSUE THREAD

**Issue by kubrickfr** [bitwarden/core#101] opened 2017-10-13 11:27 UTC
Support certificate pinning for API server using HPKP *and* enforce it in the Apps & plug-ins.

**Comment by petervnv** [comment] 2017-10-15 15:07
+1. 
I agree 100%! Certificate pinning is a must for any serious security software nowadays.

**Comment by tanto259** [comment] 2017-10-31 10:59
I don't think this will be necessary. Plus, locally installed roots would bypass HPKP.

Chrome will most likely remove HPKP support by May 2018:
https://groups.google.com/a/chromium.org/d/msg/blink-dev/he9tr7p3rZ8/eNMwKPmUBAAJ

Additionally, Edge and Safari does not support HPKP. Mozilla will also most likely follow Google decision. Most, if not all, Chromium-based browser will also follow Google decision.

---

But, I definitely would support the use of other security features, such as preloading HSTS with Expect-CT and Expect-Staple also preloaded. 

The problem is, I noticed that the main website is on GitHub Pages, in which you cannot add custom HTTP headers. Therefore, can I recommend [Netlify](https://www.netlify.com) instead? They allow custom HTTP headers and redirects.

**Comment by kspearrin** [comment] 2018-07-27 15:23
Pinning is not planned, though we have significantly improved security headers since moving to a proxy where we can control them.

**Closed by kspearrin** 2018-07-27 15:23 UTC

**Comment by gustavodagostin** [comment] 2019-03-11 15:05
There should be some way that guarantees no MITM is being performed in the communication between client and server.
Corporate firewalls do this (Man-In-The-Middle) on a regular basis.
